services:
  - type: web
    name: img-to-blocks
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
